name: Test

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.4.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change workdir
        run: go work use .
      - name: Run Test
        run: go test -v ./...
